<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# **Exercise 1**

| **Term** | **Brief description** |
| :--- | :--- |
| Subsetting | Selecting a subset of data |
| Indexing | Selecting one value of the data |
| Slicing | Selecting a range of the data |
| Masking | *Using a True/False question to select a subset of data* |

# **Exercise 2**

In [36]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

print(np_array_2d[:10,0])  # results for other steps do not appear without 'print' 

print(np_array_2d[:10,0].astype(int))

print(np_array_2d[:10,0].astype(int)%2)

print(np_array_2d[:10,0].astype(int)%2==1)

mask = np_array_2d[:10,0].astype(int)%2==1

np_array_2d[mask]

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
[ 1  3  2  4  5  7  6  8 10  9]
[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]


array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

# **Exercise 3**

In [114]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

mask = array > 50
mask2 = array == 50

array[mask] = 1
array[mask2] = 0
print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [116]:
# extra

array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

array2 = np.where (array < 50, -1, array)
array3 = np.where (array2 > 50, 1, array2)
array4 = np.where (array3 == 50, 0, array3)
print(array4)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
